version: "3.8"

services:
    app:
        build: .
        ports:
            - "3000:3000"
        restart: unless-stopped
        environment:
            - PORT=3000
            - HOST=0.0.0.0
            - DEBUG=1
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--spider",
                    "-q",
                    "http://localhost:3000/health",
                ]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 5s
        networks:
            coolify-network:
                aliases:
                    - fastify-app
        labels:
            - coolify.network.name=i0ws4goo84gsw0c0s4oskkw8
            - coolify.healthcheck.port=3000
            - coolify.healthcheck.path=/health

networks:
    coolify-network:
        external: true
        name: i0ws4goo84gsw0c0s4oskkw8
