version: "3.8"

services:
    app:
        build: .
        ports:
            - "3000:3000"
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--spider",
                    "-q",
                    "http://localhost:3000/health",
                ]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 5s
        labels:
            - traefik.enable=true
            - traefik.http.routers.fastify-app.rule=Host(`tgw4ow0g0gk88488g4wowc4c.18.193.128.202.sslip.io`)
            - traefik.http.services.fastify-app.loadbalancer.server.port=3000
